allowBuilds:
  bufferutil: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - '@jsonjoy.com/fs-core@4.68.1'
  - '@jsonjoy.com/fs-fsa@4.68.1'
  - '@jsonjoy.com/fs-node-builtins@4.68.1'
  - '@jsonjoy.com/fs-node-to-fsa@4.68.1'
  - '@jsonjoy.com/fs-node-utils@4.68.1'
  - '@jsonjoy.com/fs-node@4.68.1'
  - '@jsonjoy.com/fs-print@4.68.1'
  - '@jsonjoy.com/fs-snapshot@4.68.1'
  - antd@6.6.0
  - memfs@4.68.1
onlyBuiltDependencies:
  - bufferutil
  - utf-8-validate
